# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        cooking: 3
        recipe: 3
        graph generation: 3
        natural language understanding: 3
        graph neural network: 1
        generation: 1


# 通知の閾値
score_threshold: 3
